# 변수, 텐서, 계산그래프

## #01. 작업준비

패키지 가져오기

In [3]:
import tensorflow as tf
import numpy as np

## #02. 변수의 이해

학습을 위한 가설이 있다면

$$
f(x) = W * x + b
$$
입력데이터가 x일 때 W와 b는 텐서플로우가 학습을 통해 스스로 구해야 하는 값이다.

이를 변수라하고, 벼수형은 variable타입의 객체로 생성된다.

변수는 생성할 때 그 값에따라 압묵적 타입과 명시적 타입으로 구분된다.

### 암묵적 타입의 변수 생성하기


In [2]:
x = tf.Variable(123)
tf.print(x)
y= tf.Variable(x*100)
tf.print(y)

123
12300


### 명시적 타입의 변수 생성하기
tf.Variable() 함수에 데이터 타입을 의미하는 dtype파라미터 전달

In [4]:
x = tf.Variable(123,dtype=tf.float32)
tf.print(x)

123


### 데이터 타입 종류


- tf.float16: 16-bit half-precision floating-point.
- tf.float32: 32-bit single-precision floating-point.
- tf.float64: 64-bit double-precision floating-point.
- tf.bfloat16: 16-bit truncated floating-point.
- tf.complex64: 64-bit single-precision complex.
- tf.complex128: 128-bit double-precision complex.
- tf.int8: 8-bit signed integer.
- tf.uint8: 8-bit unsigned integer.
- tf.uint16: 16-bit unsigned integer.
- tf.uint32: 32-bit unsigned integer.
- tf.uint64: 64-bit unsigned integer.
- tf.int16: 16-bit signed integer.
- tf.int32: 32-bit signed integer.
- tf.int64: 64-bit signed integer.
- tf.bool: Boolean.
- tf.string: String.
- tf.qint8: Quantized 8-bit signed integer.
- tf.quint8: Quantized 8-bit unsigned integer.
- tf.qint16: Quantized 16-bit signed integer.
- tf.quint16: Quantized 16-bit unsigned integer.
- tf.qint32: Quantized 32-bit signed integer.
- tf.resource: Handle to a mutable resource.
- tf.variant: Values of arbitrary types.

## #03. 텐서

텐서란 배열의 집합을 의미하며 배열의 차수에 따라 불리는 이름이 바뀐다.

파이선에서는 텐서는 numpy array로 표현한다.
| 이름 | 설명 |
|--|--|
| Tensor | 수학적인 개념으로 데이터의 배열을 의미. |
| Rank | 텐서의 차원. numpy의 shape으로 확인 가능 |

### 배열의 종류

| Rank | Type | 설명 | Example |
| -- | -- | -- | -- |  
| 0 | scalar | 랭크가 0인 배열 |  [1] |
| 1 | vector | 원소가 2개 이상인 1차 배열 | [1,2] |
| 2 | matrix | 2차 배열 | [[1,2],[2,3]] |
| 3 | tensor | 3차 배열 |  [[[1,2],[2,3]],[[1,2],[2,3]]] |
| n | n-tansor | n차 배열 | |


### 랭크가 0인 배열 -> 스칼라

In [6]:
a= 100
ts1 = np.array(a)

print(ts1.shape)
ts1

()


array(100)

### 랭크가 1인 배열 -> 백터 

In [8]:
b = [1,2,3]
ts2 = np.array(b)
print(ts2.shape)
ts2

(3,)


array([1, 2, 3])

### 랭크가 2인 배열 -> 행렬

In [9]:
c = [ [10, 20, 30], [100, 200, 300] ]
ts3 = np.array(c)
print(ts3.shape)
ts3

(2, 3)


array([[ 10,  20,  30],
       [100, 200, 300]])

### 랭크가 3인 배열 -> 텐서


In [12]:
hello = [[-1,-2,-3],[1,2,3]]
world = [[-1,0,1],[1,0,-1]]
d= [hello,world]

ts4 = np.array(d)
print(ts4.shape)
ts4

(2, 2, 3)


array([[[-1, -2, -3],
        [ 1,  2,  3]],

       [[-1,  0,  1],
        [ 1,  0, -1]]])

## #03. 이진 그래프 (계산 그래프)


- Computational Graph
- 컴퓨터 공학에서 정의하는 노드와 엑지로 이루어진 자료구조
- 텐서들이 계산 그래프 구조를 통해 노드에서 다른 노드로 이동
- 텐서플로우 라이브러리는 그래프 구조를 먼저 정의하고, 정의한 그래프에서 실제 텐서들을 흘려보내도록 하는 디자인


### 명시적 타입을 갖는 노드 정의
print 함수로 출력할 경우 노드의 정보만 출력될 뿐 실제값이 출력 되지는 않는다.

실제값을 확인하기 위해서는 tf.print()

In [13]:
node1 = tf.constant(3.0,dtype=tf.float32,name='hello')
print(node1)
tf.print(node1)

tf.Tensor(3.0, shape=(), dtype=float32)
3


### 암묵적 타입을 갖는 노드 정의 

In [14]:
node2 = tf.constant(4.0,name='world')
print(node2)
tf.print(node2)

tf.Tensor(4.0, shape=(), dtype=float32)
4


### 두개의 노드의 값을 더하는 연산을 수행하는 node3을 정의

In [15]:
node3 = tf.add(node1,node2)
print(node3)
tf.print(node3)

tf.Tensor(7.0, shape=(), dtype=float32)
7


In [ ]:
지금 머신러닝중에 회귀분석이랑 로지스틱 회귀분석 두개만하고 바로 텐서플로우로 넘어갔는데, 