# Numpy

### #01. NumPy 개요

- 수학이나 과학에서 쓰이는 각종 공식이 포함되어 있음. 
- 배열을 쉽게 처리할 수 있도록 지원하는 패키지. 


#### 1) NumPy의 역할 
- 데이터 분석을 수행하기 위해 데이터를 숫자형식으로 변환
- 데이터 저장 및 가공의 효율성을 위해 NumPy 등장 
- list -> numpy -> serise -> dataframe
- numpy는 원소의 타입이 서로 다른것을 허용하지 않음.


### 2) NumPy 패키지 사용

In [2]:
import numpy


#### 1) 넘파이 배열 생성과 기본 활용

In [4]:
arr = numpy.array([1,3,5,7,9])

size = len(arr)
print(size)

5


#### 2) 넘파이 배열 특성

- 넘파이는 원소의 타입이 서로 다른 것을 허용 x
- 가장 포괄적인 형태의 자료형으로 통일 



In [6]:
arr = numpy.array([1,2.4,3,'4.6'])
arr

array(['1', '2.4', '3', '4.6'], dtype='<U32')

In [8]:
arr = numpy.array([1,2.4,3,4.6], dtype="int")
arr

array([1, 2, 3, 4])

#### 3) numpy 배열의 기초 통계값

In [13]:
grade = numpy.array([82, 77, 91, 88])
s1  = numpy.sum(grade)
print(s1)
print(numpy.average(grade))
print(numpy.min(grade))
print(numpy.max(grade))

338
84.5
77
91


#### 4) numpy 배열의 각 원소에 대한 연산

In [14]:
new = ( grade *2 ) /5 + 10
new

array([42.8, 40.8, 46.4, 45.2])

#### 5) numpy 배열의 기본 인덱싱, 슬라이싱



In [16]:
grade = numpy.array([82, 77, 91, 88])

print(grade[1:3])
print(grade[2:])



[77 91]
[91 88]


#### 6) 조건에 맞는 값 추출

In [17]:
bool_array = numpy.array([True,False,True,False])
bool_array

array([ True, False,  True, False])

In [22]:
result2 = grade[(grade >= 80) & (grade <90)]
print(result2)

[82 88]


### #03. 2차배열

#### 1) 넘파이 2차배열 생성 및 기본정보 조회

In [13]:
import numpy
grade = numpy.array([[98,72,80,64],
                    [88,90,80,72],
                    [92,88,82,76]])

print(grade)
print(grade.ndim)
print(grade.shape)

print(grade[0,1])
print(grade[0][1])
print(grade[1:3][1])

[[98 72 80 64]
 [88 90 80 72]
 [92 88 82 76]]
2
(3, 4)
72
72
[92 88 82 76]


In [ ]:
import numpy
grade = numpy.array([[98,72,80,64],
                    [88,90,80,72],
                    [92,88,82,76]])

print(grade)
print(grade.ndim)
print(grade.shape)

print(grade[0,1])
print(grade[0][1])
print(grade[1:3][1])

[[98 72 80 64]
 [88 90 80 72]
 [92 88 82 76]]
2
(3, 4)
72
72
[92 88 82 76]
